version: '3.7'
services:
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - app-tier

  fastapi:
    container_name: web
    build: .
    restart: always
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/api_token
    ports:
      - "8000:8000"
    networks:
      - app-tier
    depends_on:
      - redis
volumes:
  postgres_data:

networks:
  app-tier:
    driver: bridge
